# fly.toml app configuration file generated for prairie-plants-bold-night-7191 on 2024-12-16T13:46:41-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = 'prairie-plants-bold-night-7191'
primary_region = 'ord'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:migrate'  # Changed from db:prepare since using Postgres

[env]
  PORT = "3000"
  MALLOC_ARENA_MAX = "2"
  RAILS_MAX_THREADS = "2"
  WEB_CONCURRENCY = "1"
  # Remove DATABASE_URL since it's set as a secret

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  
  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[checks]
  [checks.status]
    port = 3000
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false
    [checks.status.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  count = 1

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'