# fly.toml app configuration file generated for prairie-plants on 2025-02-27T11:41:20-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'prairie-plants'
primary_region = 'sea'
console_command = '/rails/bin/rails console'

[env]
  PORT = "3000"
  DATABASE_URL="postgresql://postgres:admin@localhost:5432/prairie_plants"



[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

[[vm]]
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 1
