# fly.toml app configuration file generated for prairie-plants-dark-breeze-5676 on 2025-01-28T16:47:20-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'prairie-plants-dark-breeze-5676'
primary_region = 'ord'
console_command = '/rails/bin/rails console'

[build]
  [build.args]
    BUNDLE_WITHOUT = "development:test"
    BUNDLE_DEPLOYMENT = "true"
    BUNDLE_PATH = "/app/vendor/bundle"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/up'
    protocol = 'http'
    tls_skip_verify = false

    [http_service.checks.headers]
      X-Forwarded-Proto = 'https'

    [[http_service.ports]]
    handlers = ["http"]
    port = 3000


[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  AWS_REGION = "us-east-2"
  S3_BUCKET_NAME = "prairieplants"
  STRIPE_PUBLISHABLE_KEY = "pk_test_51QUz6cKk6iqXFcWtM5VayayFMzrFUZVzGsFIu3pdqC0IfRYDKFHCSUSnF4LfHLoViMc6cexttjhk7PjO4Kds9rKv006AQyft7Z"
  RAILS_ENV = "production"
  PORT = "3000"
  BINDING = "0.0.0.0"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

# Allow outbound HTTP requests
[experimental]
  allowed_public_ports = [80, 443, 3000]